spring:
  application:
    name=DriveApi

  Jpa:
    hibernate:
      show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
